using BellaBaxter.SourceGenerator;
using Xunit;

namespace BellaBaxter.SourceGenerator.Tests;

public class CodeEmitterTests
{
    private static SecretsManifest BuildManifest() => new()
    {
        Version     = "1",
        Project     = "my-app",
        Environment = "dev",
        FetchedAt   = "2026-03-01T00:00:00Z",
        Secrets     =
        [
            new() { Key = "DATABASE_URL",  Type = "ConnectionString", Description = "Postgres URL" },
            new() { Key = "MAX_RETRIES",   Type = "Integer" },
            new() { Key = "FEATURE_FLAG",  Type = "Boolean" },
            new() { Key = "API_KEY",       Type = "String" },
            new() { Key = "SERVICE_URL",   Type = "Url" },
            new() { Key = "INSTANCE_ID",   Type = "Guid" },
        ]
    };

    [Fact]
    public void Emit_ContainsClassDeclaration()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "MyApp.Config");
        Assert.Contains("public sealed partial class BellaAppSecrets", src);
    }

    [Fact]
    public void Emit_WrapsInNamespace()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "MyApp.Config");
        Assert.Contains("namespace MyApp.Config", src);
    }

    [Fact]
    public void Emit_NoNamespace_OmitsNamespaceBlock()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.DoesNotContain("namespace", src);
    }

    [Fact]
    public void Emit_PascalCasesPropertyNames()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.Contains("public string DatabaseUrl =>", src);
        Assert.Contains("public int MaxRetries =>", src);
        Assert.Contains("public bool FeatureFlag =>", src);
        Assert.Contains("public string ApiKey =>", src);
        Assert.Contains("public System.Uri ServiceUrl =>", src);
        Assert.Contains("public System.Guid InstanceId =>", src);
    }

    [Fact]
    public void Emit_IntegerPropertyUsesIntParse()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.Contains("int.Parse(_env(\"MAX_RETRIES\"))", src);
    }

    [Fact]
    public void Emit_BooleanPropertyUsesStringEquals()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.Contains("_env(\"FEATURE_FLAG\")", src);
        Assert.Contains("string.Equals", src);
    }

    [Fact]
    public void Emit_DescriptionAppearsInXmlDoc()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.Contains("/// <summary>Postgres URL</summary>", src);
    }

    [Fact]
    public void Emit_AutoGeneratedHeaderPresent()
    {
        var src = CodeEmitter.Emit(BuildManifest(), "BellaAppSecrets", "");
        Assert.Contains("<auto-generated>", src);
        Assert.Contains("BellaBaxter.SourceGenerator", src);
    }

    [Theory]
    [InlineData("DATABASE_URL",   "DatabaseUrl")]
    [InlineData("API_KEY",        "ApiKey")]
    [InlineData("MY_SECRET_VAR",  "MySecretVar")]
    [InlineData("SINGLE",         "Single")]
    [InlineData("already_lower",  "AlreadyLower")]
    public void ToPascalCase_Converts(string input, string expected)
    {
        Assert.Equal(expected, CodeEmitter.ToPascalCase(input));
    }
}
