// Emits the BellaAppSecrets.g.cs source code from a SecretsManifest.

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BellaBaxter.SourceGenerator
{
    internal static class CodeEmitter
    {
        public static string Emit(SecretsManifest manifest, string className, string namespaceName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated by BellaBaxter.SourceGenerator.");
            sb.AppendLine($"// Project: {manifest.Project}  Environment: {manifest.Environment}");
            sb.AppendLine($"// Fetched: {manifest.FetchedAt}");
            sb.AppendLine("// Do not edit this file manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = hasNamespace ? "    " : "";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine(
                $"{indent}/// Typed access to Bella secrets for project <c>{manifest.Project}</c>"
            );
            sb.AppendLine($"{indent}/// environment <c>{manifest.Environment}</c>.");
            sb.AppendLine(
                $"{indent}/// Values are read from <see cref=\"Microsoft.Extensions.Configuration.IConfiguration\"/> when"
            );
            sb.AppendLine(
                $"{indent}/// injected via DI (recommended with AddBellaSecrets), or from environment variables"
            );
            sb.AppendLine($"{indent}/// when constructed with <c>new {className}()</c>.");
            sb.AppendLine($"{indent}/// No secret values are stored in the binary.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public sealed partial class {className}");
            sb.AppendLine($"{indent}{{");

            var innerIndent = indent + "    ";

            // IConfiguration field + constructors
            sb.AppendLine(
                $"{innerIndent}private readonly Microsoft.Extensions.Configuration.IConfiguration? _configuration;"
            );
            sb.AppendLine();
            sb.AppendLine($"{innerIndent}/// <summary>");
            sb.AppendLine(
                $"{innerIndent}/// Parameterless constructor — reads secrets from <see cref=\"System.Environment\"/>."
            );
            sb.AppendLine(
                $"{innerIndent}/// Use <c>bella run -- &lt;app&gt;</c> or load a .env file before constructing."
            );
            sb.AppendLine($"{innerIndent}/// </summary>");
            sb.AppendLine($"{innerIndent}public {className}() {{ }}");
            sb.AppendLine();
            sb.AppendLine($"{innerIndent}/// <summary>");
            sb.AppendLine(
                $"{innerIndent}/// DI constructor — reads secrets from <paramref name=\"configuration\"/>."
            );
            sb.AppendLine(
                $"{innerIndent}/// Register via <c>builder.Services.AddBellaTypedSecrets&lt;{className}&gt;()</c>"
            );
            sb.AppendLine(
                $"{innerIndent}/// so ASP.NET Core injects this automatically."
            );
            sb.AppendLine($"{innerIndent}/// </summary>");
            sb.AppendLine(
                $"{innerIndent}public {className}(Microsoft.Extensions.Configuration.IConfiguration configuration)"
            );
            sb.AppendLine($"{innerIndent}    => _configuration = configuration;");
            sb.AppendLine();

            // Instance helper — prefers IConfiguration, falls back to Environment
            sb.AppendLine($"{innerIndent}private string _env(string key) =>");
            sb.AppendLine($"{innerIndent}    _configuration?[key]");
            sb.AppendLine($"{innerIndent}    ?? System.Environment.GetEnvironmentVariable(key)");
            sb.AppendLine($"{innerIndent}    ?? throw new System.InvalidOperationException(");
            sb.AppendLine(
                $"{innerIndent}        $\"Required secret '{{key}}' is not set in IConfiguration or the environment.\");"
            );
            sb.AppendLine();

            // Split secrets: flat (no __) vs sectioned (contains __ → nested class)
            var flatSecrets = manifest.Secrets
                .Where(s => !string.IsNullOrWhiteSpace(s.Key) && !s.Key.Contains("__"))
                .ToList();

            var sections = manifest.Secrets
                .Where(s => !string.IsNullOrWhiteSpace(s.Key) && s.Key.Contains("__"))
                .GroupBy(s => s.Key.Split(new[] { "__" }, 2, System.StringSplitOptions.None)[0])
                .ToList();

            // Flat properties
            foreach (var secret in flatSecrets)
            {
                var propName = ToPascalCase(secret.Key);
                var csType = TypeMapper.GetCSharpType(secret.Type);
                var getter = TypeMapper.BuildGetterExpression(secret.Type, $"_env(\"{secret.Key}\")");

                if (!string.IsNullOrWhiteSpace(secret.Description))
                    sb.AppendLine($"{innerIndent}/// <summary>{EscapeXml(secret.Description!)}</summary>");

                sb.AppendLine($"{innerIndent}public {csType} {propName} => {getter};");
                sb.AppendLine();
            }

            // Sectioned groups — one nested class per __ prefix
            foreach (var section in sections)
            {
                // Use the raw prefix as-is (preserves existing casing, e.g. "ConnectionStrings")
                var sectionName = section.Key;
                var sectionClassName = sectionName + "Section";

                sb.AppendLine($"{innerIndent}/// <summary>Secrets under the <c>{EscapeXml(sectionName)}__*</c> prefix.</summary>");
                sb.AppendLine($"{innerIndent}public {sectionClassName} {sectionName} => new {sectionClassName}(_configuration);");
                sb.AppendLine();

                sb.AppendLine($"{innerIndent}/// <summary>Typed access to <c>{EscapeXml(sectionName)}__*</c> secrets.</summary>");
                sb.AppendLine($"{innerIndent}public sealed class {sectionClassName}");
                sb.AppendLine($"{innerIndent}{{");
                var secIndent = innerIndent + "    ";

                sb.AppendLine($"{secIndent}private readonly Microsoft.Extensions.Configuration.IConfiguration? _configuration;");
                sb.AppendLine();
                sb.AppendLine($"{secIndent}internal {sectionClassName}(Microsoft.Extensions.Configuration.IConfiguration? configuration)");
                sb.AppendLine($"{secIndent}    => _configuration = configuration;");
                sb.AppendLine();

                // Section _env: IConfiguration uses : separator, env vars use __ separator
                sb.AppendLine($"{secIndent}private string _env(string key) =>");
                sb.AppendLine($"{secIndent}    _configuration?[\"{sectionName}:\" + key]");
                sb.AppendLine($"{secIndent}    ?? System.Environment.GetEnvironmentVariable(\"{sectionName}__\" + key)");
                sb.AppendLine($"{secIndent}    ?? throw new System.InvalidOperationException(");
                sb.AppendLine($"{secIndent}        $\"Required secret '{sectionName}__{{key}}' is not set in IConfiguration or the environment.\");");
                sb.AppendLine();

                foreach (var secret in section)
                {
                    var subKey = secret.Key.Split(new[] { "__" }, 2, System.StringSplitOptions.None)[1];
                    var propName = ToPascalCase(subKey);
                    var csType = TypeMapper.GetCSharpType(secret.Type);
                    var getter = TypeMapper.BuildGetterExpression(secret.Type, $"_env(\"{subKey}\")");

                    if (!string.IsNullOrWhiteSpace(secret.Description))
                        sb.AppendLine($"{secIndent}/// <summary>{EscapeXml(secret.Description!)}</summary>");

                    sb.AppendLine($"{secIndent}public {csType} {propName} => {getter};");
                    sb.AppendLine();
                }

                sb.AppendLine($"{innerIndent}}}");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
                sb.AppendLine("}");

            return sb.ToString();
        }

        internal static string ToPascalCase(string envKey)
        {
            var sb = new StringBuilder();
            var nextUpper = true;
            foreach (var ch in envKey)
            {
                if (ch == '_' || ch == '-')
                {
                    nextUpper = true;
                }
                else if (nextUpper)
                {
                    sb.Append(char.ToUpperInvariant(ch));
                    nextUpper = false;
                }
                else
                {
                    sb.Append(char.ToLowerInvariant(ch));
                }
            }
            return sb.Length == 0 ? "_" : sb.ToString();
        }

        private static string EscapeXml(string s) =>
            s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
