// BellaBaxter.SourceGenerator — shared manifest model (netstandard2.0)
// This file is intentionally self-contained (no System.Text.Json dependency).

using System.Collections.Generic;

namespace BellaBaxter.SourceGenerator
{
    /// <summary>
    /// Root structure of bella-secrets.manifest.json.
    /// Generated by the BellaSecretsManifestTask MSBuild task and consumed
    /// by the BellaSecretsSourceGenerator Roslyn generator.
    /// </summary>
    internal sealed class SecretsManifest
    {
        /// <summary>Schema version, currently "1".</summary>
        public string Version { get; set; } = "1";

        /// <summary>Bella project slug.</summary>
        public string Project { get; set; } = "";

        /// <summary>Bella environment slug (dev / staging / prod …).</summary>
        public string Environment { get; set; } = "";

        /// <summary>UTC ISO-8601 timestamp of when the manifest was fetched.</summary>
        public string FetchedAt { get; set; } = "";

        /// <summary>Secret entries — key metadata only, no values.</summary>
        public List<SecretEntry> Secrets { get; set; } = new List<SecretEntry>();
    }

    internal sealed class SecretEntry
    {
        /// <summary>The secret key as stored in the provider, e.g. "DATABASE_URL".</summary>
        public string Key { get; set; } = "";

        /// <summary>
        /// Bella SecretType string: String | Integer | Boolean | Float |
        /// Json | Base64 | Guid | ConnectionString | Url | CertificatePem.
        /// Defaults to "String" when not set.
        /// </summary>
        public string Type { get; set; } = "String";

        /// <summary>Optional human-readable description surfaced in IDE tooltips.</summary>
        public string? Description { get; set; }
    }
}
